register(GRAMPLET,
    id   = 'QRCode Relationship Calculator Gramplet',
    name = _('QRCode Relationship Calculator Gramplet'),
    description = _("Determines the relationship between two individuals whose information is stored on two separate QRCodes"),
    version = '1.0',
    gramps_target_version = '4.1',
    status = UNSTABLE,
    fname = 'Relations.py',
    include_in_listing = False,
    gramplet = 'QRCodeRelationshipGramplet',
    gramplet_title=_("QRCode Relationship Calculator Gramplet"),
     )
